name: riverpod_todos_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  queen_validators: ^1.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  auto_route_generator: ^7.3.2


flutter:

  uses-material-design: true




